### ISSUE TITLE
[NEW MODULE] Tadukoo Look & Feel

### ISSUE THREAD

**Issue by Tadukoo** [Tadukooverse/TadukooView#1]
**Describe the new module you're proposing**
A customizable look & feel that makes it easier to customize the style of the default Java components.

**Why should we add this new module?**
It will make it easier to customize the style of programs.

**Describe alternatives you've considered**
In Old Tadukoo Util, I was creating my own custom components in order to have them look the way I wanted them to. That process is needlessly more complicated as it avoids using the default Java components entirely (reinventing the wheel for those components). This approach would eliminate that need.

**Additional context**
This was technically already started and is partially present in Alpha v.0.1, but this Issue will be worded for the full project/process instead of just what needs done yet, in order to have it more properly documented here.

Note that development on this happened in the Tadukoo Util project before it was moved here, which is part of why some stuff is done already and other oddities with this item.

**Changes Needed**
The ultimate goal (at this point at least, future changes will involve more) is to replace the MetalLookAndFeel with a new TadukooLookAndFeel that allows for more customization through use of a theme, and customization on the level of individual components themselves too.

- [x] First of all, we need to create a LookAndFeel class extending MetalLookAndFeel and override the default and/or required methods
- [x] We need a Theme class (with a builder) to hold all the customizable items in, along with a ThemeFactory (to be able to easily create themes based off others - e.g. Metal, but with the customizable buttons

We will need to allow customizations for the following general items:
- [x] Paints (how to color pieces of the components, can be gradients, solid colors, textures, etc.)
- [x] Fonts (includes making it easier to choose a font you want to use from some standards)
- [x] Shapes (what shape components/pieces of them take)
- [x] Borders
- [x] Support using different component UI classes (e.g. use all the default Tadukoo ones, except we want the Metal Button UI) (just involves including Class<ButtonUI> etc. in Tadukoo Theme, which would be added on a per-component UI basis)
- [x] Support adding custom defaults to the defaults table (by category)

Other Changes to be made:
- [x] Add Font Resource Loading to Form Field Builder (#3)
- [x] Add Sizable Paints interface for Components (#6)
- [x] JUnit testing for Look & Feel (#7)
- [x] Move Title Position enum out of Tadukoo Theme (#8)
- [x] Create Shape Info UIResource (#9)
- [x] Allow for No Paint on Components (#11)
- [x] Allow for No Border on Components (#12)
- [x] Create Component Interfaces (#13)
- [x] Create Component UI Interfaces (#14)
- [x] Do some reorganization (#15)
- [x] Change Form Fields to store all FontResourceLoader settings and pass them down to their components (#17)

We will need to support those customizations in the components that Metal uses:
- [x] ButtonUI (#2)
- [ ] CheckBoxUI (#19)
- [ ] ComboBoxUI (#20)
- [ ] DesktopIconUI
- [ ] FileChooserUI
- [ ] InternalFrameUI
- [x] LabelUI (#10)
- [ ] PopupMenuSeparatorUI
- [ ] ProgressBarUI
- [ ] RadioButtonUI
- [ ] RootPaneUI
- [ ] ScrollBarUI
- [ ] ScrollPaneUI (#22)
- [ ] SeparatorUI
- [ ] SliderUI
- [ ] SplitPaneUI
- [ ] TabbedPaneUI
- [ ] TextFieldUI (#21)
- [ ] ToggleButtonUI
- [ ] ToolBarUI
- [ ] ToolTipUI
- [ ] TreeUI

There are other components that are in Tadukoo Form/Components that will need new UI classes here, even though Metal specifically doesn't have them, but Basic Look & Feel does:
- [ ] PasswordFieldUI (#23)
- [ ] SpinnerUI (#26)
- [ ] TableUI (#24)

Other customization items to be done:
- [ ] Customizations in Date Form Field (#27)
- [ ] Customizations in String Form Field (#18)
- [ ] Customizations in Table Form Field (#25)

Items Missed during the above Customizations:
- [x] Allow setting Button shape in Button Form Field (#16)

Undecided Stuff
- Make it so the focus can use different shapes?
  - If this is done, stuff needs done with insets - using the normal insets for the rectangle with cut corners puts the focus outside the button, but using 1/2 the insets size for it looks okay

**Comment by Tadukoo** [comment]
This will span multiple milestones and not be completed for a while due to how big a project it is. Currently I don't know what milestone it will be completed in (it probably won't be Alpha v.0.4, but may be 0.5 or 0.6 perhaps

**Comment by Tadukoo** [comment]
Added the other modules as labels because they're being impacted by this too - this is a very wide-reaching goal

**Comment by Tadukoo** [comment]
This needs to be re-worded now that Tadukoo Look & Feel and Tadukoo Form are no longer part of Tadukoo View.
It may actually make more sense to close this (to keep for historical purposes) and make a new ticket

**Comment by Tadukoo** [comment]
Closing as this is now covered by #55 and its subtasks
