### ISSUE TITLE
[FEATURE] Create Component Interfaces

### ISSUE THREAD

**Issue by Tadukoo** [Tadukooverse/TadukooView#13]
**Describe the solution you'd like**
Create interfaces for Components, so they don't need to extend a collection of interfaces for the customizations in the Component classes themselves. Also this can help in the Look & Feel with installing defaults.

**Is your feature request related to a problem? Please describe.**
Not really

**Describe alternatives you've considered**
None

**Additional context**
Part of #1

**TODO Changes**
- [x] Create TComponent interface
  - [x] Uses HasSizablePaints and Shaped
- [x] Create TButton interface
  - [x] Uses TComponent and HasSelectAndFocusPaints and HasDisabledTextPaint
- [x] Create TLabel interface
  - [x] Uses TComponent and HasDisabledForegroundPaint
- [x] Change Tadukoo Button UI to look for TButton interface for install/uninstall defaults
