### ISSUE TITLE
[FEATURE] CheckBoxUI Customizations

### ISSUE THREAD

**Issue by Tadukoo** [Tadukooverse/TadukooView#19]
**Describe the solution you'd like**
Allow for customizations in how checkboxes are shown using Tadukoo Look & Feel

**Is your feature request related to a problem? Please describe.**
No

**Describe alternatives you've considered**
None

**Additional context**
Part of #1

**TODO Changes**
- [ ] Create a new TCheckBox interface that uses interfaces for the customizations
- [ ] Create a new TadukooCheckBox class extending JCheckBox with customizations
  - [ ] TODO: List customizations
- [ ] Create a new TadukooCheckBoxUI class for this
  - [ ] TODO: List customizations
- [ ] Include the customizations in BooleanFormField
  - [ ] TODO: List customizations
- [ ] Include the customizations in TadukooTheme
  - [ ] TODO: List customizations
- [ ] Include the customizations in Tadukoo Look & Feel
  - [ ] TODO: List customizations
- [ ] Include the customizations in TadukooThemeFactory
  - [ ] TODO: List customizations

**Comment by Tadukoo** [comment]
Split up into #56 (for the part contained in Tadukoo View still), Tadukooverse/TadukooLookAndFeel#2 (for the part specific now to the Look & Feel project), and Tadukooverse/TadukooForm#8 (for the part specific now to the Form project)
