### ISSUE TITLE
[FEATURE] TableUI Customizations

### ISSUE THREAD

**Issue by Tadukoo** [Tadukooverse/TadukooView#24]
**Describe the solution you'd like**
Allow for customizations in how tables are shown using Tadukoo Look & Feel

**Is your feature request related to a problem? Please describe.**
No

**Describe alternatives you've considered**
None

**Additional context**
Part of #1

**TODO Changes**
- [ ] Create a new TTable interface that uses interfaces for the customizations
- [ ] Create a new TadukooTable class extending JTable with customizations
  - [ ] TODO: List customizations
- [ ] Create a new TadukooTableUI class for this
  - [ ] TODO: List customizations
- [ ] Include the customizations in TadukooTheme
  - [ ] TODO: List customizations
- [ ] Include the customizations in Tadukoo Look & Feel
  - [ ] TODO: List customizations
- [ ] Include the customizations in TadukooThemeFactory
  - [ ] TODO: List customizations

**Comment by Tadukoo** [comment]
Split into #61 (for Tadukoo View specific pieces), Tadukooverse/TadukooLookAndFeel#7 (for Look & Feel project pieces), and Tadukooverse/TadukooForm#6 (for Tadukoo Form project pieces)
