### ISSUE TITLE
[FEATURE] SpinnerUI Customizations

### ISSUE THREAD

**Issue by Tadukoo** [Tadukooverse/TadukooView#26]
**Describe the solution you'd like**
Allow for customizations in how spinners are shown using Tadukoo Look & Feel

**Is your feature request related to a problem? Please describe.**
No

**Describe alternatives you've considered**
None

**Additional context**
Part of #1

**TODO Changes**
- [ ] Create a new TSpinner interface that uses interfaces for the customizations
- [ ] Create a new TadukooSpinner class extending JSpinner with customizations
  - [ ] TODO: List customizations
- [ ] Create a new TadukooSpinnerUI class for this
  - [ ] TODO: List customizations
- [ ] Put the customizations in NumberFormField and its subclasses
  - [ ] TODO: List customizations
- [ ] Include the customizations in TadukooTheme
  - [ ] TODO: List customizations
- [ ] Include the customizations in Tadukoo Look & Feel
  - [ ] TODO: List customizations
- [ ] Include the customizations in TadukooThemeFactory
  - [ ] TODO: List customizations

**Comment by Tadukoo** [comment]
Split into #60 (for Tadukoo View specific pieces), Tadukooverse/TadukooLookAndFeel#6 (for Look & Feel project pieces), and Tadukooverse/TadukooForm#3 (for Tadukoo Form project pieces)
